accounting-json/Xero_accounting_2.0.0_swagger.json
accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

Fix paymentTerm on contact was set to ENUM PaymentTermType when it should be the PaymentTerm object.

Swaggerhub

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

When testing with Demo Company (AU) a type of "DELETE" was returned in Expense Claim Status. Hence the pull request. 
Status:
description: Current status of an expense claim – see status types
type: string
enum:
- SUBMITTED  
- AUTHORISED
- PAID
- VOIDED
**- DELETED** <= this is found missing

added DELETE type to Expense Claim Status Codes

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

When testing with Demo Company (AU) to get tax rates, a few missing Report Tax Types were discovered. I have compared & added following Report Tax Types to OAS spec as per our documentation on dev portal:
- EXEMPTCAPITAL
- EXEMPTEXPORT
- CAPITALEXINPUT
- GSTONCAPIMPORTS
- REVERSECHARGES
- PAYMENTS
- INVOICE
- CASH
- ACCRUAL
- FLATRATECASH
- FLATRATEACCRUAL
- ACCRUALS
A report on missing Report Tax Types:

added Tax Report Types

---

README.md

Alternatively you may wish to rename the yaml file to be consistent with the others, but given that may be riskier, since its impossible to know who might have links there.

Correct the Xero Identity swagger spec link

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

This is to address the edge case where we want a method to "getInvoiceAsPDF and have it return binary data and not a JSON object.
It has the same path as "getInvoice" and in order to get this edge case into the spec we used /Invoices/{InvoiceId}/pdf as the path.
This will require each language to override the path value with x-path if x-path exists.
This is how it looks in the typescript-node mustache template
const localVarPath = this.basePath + '{{#vendorExtensions}}{{#x-path}}{{{x-path}}}{{/x-path}}{{^x-path}}{{{path}}}{{/x-path}}{{/vendorExtensions}}'{{#pathParams}}

Add x-path vendor extension

---

.gitignore
accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

This is to address the edge case where we want a method to "getInvoiceAsPDF and have it return binary data and not a JSON object.
It has the same path as "getInvoice" and in order to get this edge case into the spec we used /Invoices/{InvoiceId}/pdf as the path.
This will require each language to override the path value with x-path if x-path exists.
This is how it looks in the typescript-node mustache template
const localVarPath = this.basePath + '{{#vendorExtensions}}{{#x-path}}{{{x-path}}}{{/x-path}}{{^x-path}}{{{path}}}{{/x-path}}{{/vendorExtensions}}'{{#pathParams}}
---------
Remove a duplicate Enum
-------
Explain unitdp

Add x-path vendor extension // docs // dup ENUM

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

Created unique QuoteLineAmountTypes
Added type: 'string' to the CountryCode for Organisation object - this is to test a fix on the PHP type hints

Found the LineAmountTypes are ALL CAPS for Quotes

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

Done this in an effort to help with PHP code hintings.  These ENUMs are in fact strings - but a predefined list.

Added string datatype to ENUMs

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

Adds `x-isAttachmentUpload` - then mustache template won't add `json: true` for file uploading functions so the image data can be serialized correctly

file upload x- to not add json true to headers

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

All attachment creates / updates / gets use `x-isAttachment` to ensure request data is not malformed into json.

Move x-isAttachment to response venderExtensions - and add it for all attachment related inquiries that require binary response data

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

Thanks to @lukesawyer, a missing enum in Manual Journal Object is discovered. 
Instructions to create an archived manual journal entry: 
https://central.xero.com/s/article/Void-archive-or-delete-multiple-journals#Archiveorrestorepostedmanualjournals
An example of an "ARCHIEVED" manual journal returned via API:
```
<ManualJournal>
<Date>2019-07-24T00:00:00</Date>
<Status>ARCHIVED</Status>
<LineAmountTypes>Exclusive</LineAmountTypes>
<UpdatedDateUTC>2020-02-12T01:04:32.277</UpdatedDateUTC>
<ManualJournalID>bb6cfcfc-4500-4475-bd3a-93ee512428e0</ManualJournalID>
<Narration>Being depreciation on office equipment</Narration>
<ShowOnCashBasisReports>true</ShowOnCashBasisReports>
<HasAttachments>false</HasAttachments>
</ManualJournal>
```

Added "ARCHIEVED" Status to Manual Journal Object

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

To address the use case where a queryString includes the unitdp=4 param we need to change objects with attributes that support more than two decimal points to to change the number datatype from double to float.
Objects that use LineItems are impacted
- BankTransations
- CreditNotes
- Invoices
- Receipts
the two properties that changed from double to float
- Quantity
- UnitAmount
The item object has two properties that chagned from double to float
- UnitPrice
- QuantityOnHand

Fix unit decimal point issue in objects

---

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml

getInvoiceAsPdf and getCreditNoteAsPdf
- removed "contentType" param as it's unnecessary
- changed response content type from application/octet-stream to application/pdf because it will alway return a pdf.
Update createEmployees
- add summarizeErrors param
Remove createEmployee method (singular - as this path/method)
/Employees POST is needed for updateOrCreateEmployees
Add updateOrCreateEmployees method
- with summarizeErrors param
Update createManualJournals
- add summarizeErrors param
Remove createManualJournal method (singular - as this path/method)
/ManualJournals POST is needed for updateOrCreateManualJournals
Add updateOrCreateManualJournals method
- with summarizeErrors param
Remove createOverpaymentAllocation method
Add createOverpaymentAllocations method
- with summarizeErrors …

Fix several methods

---

identity-yaml/xero-identity.yaml

Add x-is-datetime:true to use in models to define stings as Local Date Time object without timezone offset.

Update identity with new vendorExtension

---

assets-yaml/xero_assets.yaml

The Xero API returns status with initial caps not all caps.  For example the API returns "Draft".  You could POST with DRAFT, but the response is Draft.  As ENUMS this causes a mis-match.

Change casing of AssetStatus enums

---

accounting-yaml/xero_accounting.yaml

Had this typed as string. 
I've already fixed a bug in xero-node `deserialize` function which was not able to handle an integer coming back as a typed string but figured we should update spec for accuracy.

BankTransfer Amount to number

---

accounting-yaml/xero_accounting.yaml

This attribute was missing from https://github.com/XeroAPI/xero-ruby but is shown in https://developer.xero.com/documentation/api/organisation, which is where I got the description text.

add EmployerIdentificationNumber to Organisation

---

accounting-yaml/xero_accounting.yaml

As we've recently found out that we do not support certain document types for creating history via the api. Hence removing those from the OAS. These have been commented out for now, since the plan is to implement this someday.

Remove(comment out) unsupported doctypes for creating history

---

accounting-yaml/xero_accounting.yaml

With the latest release, we have extended the create notes feature to more document types. These were commented out in the specs as they weren't supported before. So undoing that.
Also adding the newly added 'RepeatingInvoiceID' returned with Get/invoices to the specifications.
Thanks

Uncommenting History and Notes specs

---

accounting-yaml/xero_accounting.yaml

was previously `TenNinteyNineContact`.
also needs to be updated in the SDKs eg https://github.com/XeroAPI/xero-php-oauth2/blob/master/lib/Models/Accounting/TenNinteyNineContact.php

fix typo in TenNinetyNineContact

---

accounting-yaml/xero_accounting.yaml

Ruby Codegen Work
* Adding enums in the model
* Adds a couple comments
* Adds x-ruby-payload and x-ruby-requestBody vendor extension(strings)
* for all POST's that require body parameters and fixes docs to use the new enum values - currently only accounting docs are fixed.
> Note, was not able to fix the specs in the mustache templates without an un-reasonable amount of scripting.. So will just add those & fix manually as new sets are layered in.
--- Needs Review ----- @SidneyAllen 
* pattern for adding dynamic language docs.. (Ruby is not able to be generated by htmlDocs2 at this point 👎  I joined their slack and am seeing if it is something I could open source contribute, or if there is another technical language reason why not..)
* Removed OrganisationEntityType enums as they were …

Dynamic language docs

---

accounting-yaml/xero_accounting.yaml

Reported by @ThirstyJarek from [a .NET SDK issue](https://github.com/XeroAPI/Xero-NetStandard/issues/200): 
Line 21777: 
QuoteStatusCodes:
description: The status of the quote. 
type: string
enum:
- DRAFT
- SENT
- DECLINED
- ACCEPTED
- INVOICED
**- DELETED**

Add DELETED enum to QuoteStatusCode in Quote schema

---

accounting-yaml/xero_accounting.yaml
payroll-au-yaml/xero-payroll-au.yaml

This PR is based on the branch [fix-attachment-contentlength-data-type](https://github.com/XeroAPI/Xero-OpenAPI/tree/fix-attachment-contentlength-data-type), please review PR [261](https://github.com/XeroAPI/Xero-OpenAPI/pull/261) first

Fix payrollau accrue leave number to boolean

---

accounting-yaml/xero_accounting.yaml

The datatype of Attachment ContentLength is "number" which result in a float/decimal in generated SDKs. 
Our API will return 500 error if a number with decimal is sent. 
Changing this to "integer" will set the type to int for all SDKs.
Reported here in .NET SDK issue [205](https://github.com/XeroAPI/Xero-NetStandard/issues/205).

change Accounting Attachment ContentLength data type to integer

---

accounting-yaml/xero_accounting.yaml
payroll-au-yaml/xero-payroll-au.yaml

This PR corrects the type of LeaveLoadingRate to "double" under LeaveType schema.
This is an [issue](https://github.com/XeroAPI/Xero-NetStandard/issues/196) reported by .NET SDK repo.

Fix payrollau payitem leaveloadingrate not double

---

xero_accounting.yaml

@Arcath @SidneyAllen 
GET https://.../Quotes/{identifier} only works with uuid quote ID unlike PurchaseOrders which accepts either PO Number or uuid.
QuoteNumber must instead be used as parameter GET https://.../Quotes?QuoteNumber=QU-0001.
https://developer.xero.com/documentation/api/quotes
https://developer.xero.com/documentation/api/purchase-orders
This PR removes getQuoteByNumber and adds QuoteNumber as a parameter to getQuotes.

adds QuoteNumber param to getQuotes

---

xero_accounting.yaml

```
TrackingOption:
externalDocs:
url: 'http://developer.xero.com/documentation/api/tracking-categories/'
properties:
TrackingOptionID:
description:  The Xero identifier for a tracking optione.g.
ae777a87-5ef3-4fa0-a4f0-d10e1f13073a
type: string
format: uuid
Name:
description:  The name of the tracking option e.g. Marketing, East (max length = 100)
maxLength: 100
type: string
Status:
```

tracking option length 50 -> 100

---

xero_accounting.yaml

Added following operations for Accounting OpenAPI spec:
- getPurchaseOrdersAttachments
- getPurchaseOrder≠AttachmentByFileName
- updatePurchaseOrderAttachmentByFileName
- createPurchaseOrderAttachmentByFileName
Tested manually in C# starter app.

Add purchaseorder attachments operations

---

xero-payroll-nz.yaml
xero_accounting.yaml

Added is-money vendor extension to all field that is related to monetary calculation so the SDKs which support Decimal type can be used. 
NumberofHours and NumberofUnit could be integers but I have made them decimal just to be safe.
I will be reaching out to NZ payroll team next week to confirm the exact type number used in the system.

Payroll nz add is money vendor extension

---

.github/issue_template.md
.github/pull_request_template.md
README.md
xero_accounting.yaml

* reverts all the request body examples from javascript objects to raw json.
* puts the node examples into a vendor extension to match the temporary ruby style of `x-<language>-requestBody`
* removes `x-related-model` vendor extension (https://trello.com/c/aBASxoFz/68-vendor-extension-audit)
* rename two problem currencies to TRY_LIRA and EMPTY_CURRENCY
* Adds PR and Issue Templates

Revert json examples

---

xero_accounting.yaml

Adding a definition for the POST /Setup endpoint including schemas for the request and response.
It allows the Setup endpoint to be added to SDKs and other tools generated from the OpenAPI spec. This is very important for conversion partners migrating to OAuth 2

Adding a definition for the setup endpoint

---

xero_files.yaml

Replaced the Enums with how the files API serializes back enums.
Got full list from @admo26: https://github.dev.xero.com/Xero/Api.Files/blob/e957f17c2703d5c63d579424ed92e0c504da18d8/project/Api.Files/Library/Model/Domain/ObjectType.cs

Files Spec fixes

---

xero_assets.yaml

Adding the disposalDate field to the Asset object. This is not a new field in the API but was missing from the docs and spec.
This field was missing from the spec

Adding the disposalDate field to the Asset object

---

xero_accounting.yaml

Discovered that this field was missing. Exists in the data and the documentation
Add missing field (DueDate) on CreditNotes (same as Invoices)

Add DueDate to CreditNotes

---

xero_accounting.yaml

According to the docs, a Date parameter is needed to call the Balance Sheet report
Add missing parameter (Date) to call Balance Sheet Report

Balance Sheet should take a date

---

xero-payroll-nz.yaml

Updated SDK to version 3.9.0
- Now refers to CalendarType class for enum options.
- Periodunit type changed from int to decimal

Fix payrollnz taxsettings periodunit int to decimal

---

xero_accounting.yaml

FieldID in ReportFields is an uuid but the API returns a string. This results the report response (GetReportBASorGST) unable to be deserialised. 
FieldID in ReportFields is changed from uuid to string

fixed ReportFields' FieldID type change from uuid to string

---

xero_accounting.yaml

GET LinkedTransactions
Added format:UUID to the following query params
LinkedTransactionID
SourceTransactionID
ContactID
TargetTransactionID
developers wishing to use an ID returned from the API as a UUID won't need to cast it as a string when using to perform a GET on LinkedTransactions endpoint.

Add missing format on query params for GET LinkedTransactions

---

xero_accounting.yaml
xero_bankfeeds.yaml

Added missing <i>invalid-end-date</i> to bankfeeds Error enum and added missing <i>CISDeduction</i> and <i>CISRate</i> to Accounting.
CISDeduction added to CreditNote, CISRate added to both CreditNote and Invoice in Accounting. 
CISRate has been changed to decimal and set as readOnly.
This adds missing values to schemas.

Added missing invalid-end-date to bankfeeds Error enum and added missing CISDeduction and CISRate to Accounting

---

xero-payroll-nz.yaml

The API may return a decimal value for this field, e.g. `7.000`
Changed the type so that this will be correctly deserialised.
Using `x-is-money` for consistency with other fields in this schema.
Provides a fix for: https://github.com/XeroAPI/Xero-NetStandard/issues/264

PayrollNZ SalaryAndWage DaysPerWeek, change from integer to double x-is-money

---

xero_accounting.yaml

Using vendor extension to define meta data for use to generate runnable code examples in java, php and python.

Add x-example and language specific param examples to generate htmlDoc2

---

xero_accounting.yaml

Credit Note Applied Amount should be a monetary field
Reported by @mogest  -> https://github.com/XeroAPI/xero-ruby/issues/117
We use OpenAPI Spec's vendor extension pattern to handle non conforming cases that fuel the logic in the templates of our SDK generation. This specifically helps ruby SDK put type as BigDecimal instead of float, as well as other similar type changes in the other 5 SDKs.
Monetary field changed to proper type

Make AppliedAmount a monetary field

---

xero_assets.yaml

filterby parameter for GET assets acts as an keyword search against the AssetName, AssetNumber, Description and AssetTypeName fields
This PR changes the enum type to string
It is currently being interpreted as enum which is blocking its function. 
Searching for AssetCode will return only the matching item: 
API documentation also confirms so:

update filterby parameter to string from a enum

---

xero-identity.yaml
xero_accounting.yaml

For identity and accounting APIs, some OpenAPI integer properties had an invalid format. The generator was producing warnings, but falling back to a float or double.
Some model properties were `type: number` and `format: int` or `format: integer`. This is invalid for OpenAPI v3.0.x The supported formats are here:
https://swagger.io/specification/#dataTypeFormat
The fix changes these to: `type: integer` and `format: int64` for the identity model (I have no idea how big that number can get) and `type: integer` and `format: int32` for the accountancy API (those numbers are counts of present and updated accounts and records, which I am *assuming* an `int32` will be sufficient for just for practical reasons. The int32/int64 choices were just my assumptions and can be changed.
The OpenAPI …

Fix invalid integer formats

---

xero_accounting.yaml

BatchPayment model added ValidationErrors array element.
Developer in C# SDK found that when using summarisedError=false, CreateBatchPayments 
Linked issue: https://github.com/XeroAPI/Xero-NetStandard/issues/324

added validationerror to batchpayment object & remove from batchpayments

---

xero_bankfeeds.yaml

Bankfeeds update to update success status codes, change the case of a param placeholder, and add TransactionType to statementLines model.
Developer in Java SDK found some inaccuracies in the Bankfeeds spec compared to online documentation and actual API responses.
Linked issues: https://github.com/XeroAPI/Xero-OpenAPI/issues/381
https://github.com/XeroAPI/Xero-OpenAPI/issues/379
https://github.com/XeroAPI/Xero-OpenAPI/issues/378

Update Bankfeeds spec to resolve issues 378,379, and 381

---

xero_accounting.yaml

Added properties to support NetStandard documentation and some minor bug fixes with x-examples.
Added csharp specific properties to enums, date objects, types and variable names to support documentation.
Fixed issues with createTaxRates, createBankTransactions, updateTaxRates, updateBankTransactions examples.
Added is_money attributes to support converting to Decimal in csharp examples.

Added C# specific values for NetStandard examples, Bug Fixes

---

xero-payroll-uk.yaml

Get methods for Employees and Timesheets incorrectly defined params to be passed by name for querying the API.  Instead it needs to be a single param called "filter" that has named params and values passed together.

Fix UK Payroll GET filters

---

xero_bankfeeds.yaml

Bankfeeds update to fix inaccuracy in error response for posting Feedconnections.
A development partner pointed out the error response and status code is incorrect for Feedconnections. The API will actually return an overall HTTP 400 but will include a sub-status per connection error in the response body. I removed the 409 from the expected responses, and updated the schema/example for the 400
https://github.com/XeroAPI/Xero-OpenAPI/issues/380

Update Bankfeeds spec to resolve issue 380

---

xero-payroll-uk.yaml

Currently we are unable to access the salary and wage information on our Xero tenant (UK) as some of our staff are on an Hourly contract instead of a Salary contract. I believe this may be a simple oversight so I have prepared a change that adds the enumeration value.
Adds the Hourly  Payment Type enum value for the UK Payroll API ensuring that salary and wage data.
N/A

Added Hourly option to SalaryAndWage paymentType

---

xero_accounting.yaml

Field incorrectly set as read-only
Brings OAuth 2.0 SDK in line with the OA1 behaviour

Remove readonly property from manulajournalline TaxAmount

---

xero-projects.yaml

Causing issues in the SDKs when the status returned isn't expected

Missing ENUM for Time entry status

---

xero_accounting.yaml

This change is adding the field AccountID on the line items for GET bank transactions endpoint.
We are exposing the AccountID for the chart of account associated on the line item. It is not available for GET and not supported for PUT and POST just yet.

Add AccountID on Bank transactions line items

---

xero_accounting.yaml

Added missing endpoints:
- /Budgets
- /Budgets/{BudgetID}
* breaking change for those using previous GST BAS reports endpoints - renamed routes to support no breaking changes to future state of adding org unique reports.
```
getReportsList
getReportFromId
```
Solves the problem of some endpoints missing in the Open API Spec but present in the site documentation
Specifically impacting GST or BAS for AUS and NZ orgs

Reports consolidation & Budgets Endpoints

---

xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

Make it a little easier for devs to grok where to add in data for the additional parameter.
Most sdks used named objects for params, but some like node, use a position pattern for function params. This tweaks the recent addition to be appended to the end of the getInvoices fn to make the breaking change a little more palatable.

Move the summary only param for getInvoices to the last parameter position

---

xero-payroll-uk.yaml

From a thread here: https://github.com/XeroAPI/xero-ruby/issues/175#issuecomment-861928921
Tracked down an earnings type that had not been reported for UK payroll yet.

Single enum add for uk payroll earnings type

---

xero_accounting.yaml

Fixed Budgets endpoint
Noticed Budgets response wasn't deserializing in the Java SDK.
- Added BudgetLines
- Made Tracking an array

add changes to the Budgets schema

---

xero_accounting.yaml

Customer reported that this time zone was missing from the Ruby SDK
Added missing ENUM

Added missing EASTERISLANDSTANDARDTIME timezone

---

xero-app-store.yml

Quick fix to remove a trailing slash on the base API url for new app store endpoints

Remove trailing slash on base url for app store

---

xero_accounting.yaml

Was set as integer which is incorrect as a decimal is typically returned.
API returns decimals, this causes some SDKs to throw an error as they were expecting an integer.
Should fix https://github.com/XeroAPI/Xero-NetStandard/issues/377

Updated Budgeted amount type 

---

xero-payroll-au.yaml

Add directors fees earnings type to the payroll AU SDK in preparation for the implementation in the API itself.
Add EarningsRate enum value ```DIRECTORSFEES``` to the Payroll AU SDK spec
This is required so app partners can prepare for integration before release of the changes to the API

Add directors fees to earnings types for AU Payroll SDK

---

xero-payroll-uk.yaml
xero_accounting.yaml

Filtering is available when retrieving a single budget, this adds support for it
Added missing EarningsRates for tips in UK Payroll

Fix GetBudget filtering and missing UK payroll earningsrates

---

xero_accounting.yaml

Reflects the new properties added the the bank transfers endpoints
New reference field added to add references to the bank transactions
You can now reconcile the from and to bank transactions on create
Because it reflects the changes in the updated API

Add new properties to bank transfers

---

xero-finance.yaml

Removed `x-is-datetime: true` as the API team released code to standardize local date-times to date-times.
Also updated a response example to be in yaml instead of json to be more consistent. 
This fix directly affects the code generator for our Java SDK 
- [`x`] Bug fix (non-breaking change that fixes an issue)

Update datetime format in finance api

---

xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

-removes `nullable: true` fields from Finance API spec
-makes `if-modified-since` header consistent to reflect `type: string` and `format: date-time`
-`nullable: true` was a leftover artifact from the internal API spec and was breaking the .NET SDK build
-`if-modified-since` header now matches format in the API docs `example: "2020-02-06T12:17:43.202-08:00"`

removes nullable fields from finance spec and makes if-modified-since header consistent

---

xero-payroll-uk.yaml

As part of the NI initiative for 2022-2023, five new codes (F, I, S, L, V) have been introduced in MVC.
This PR updates the docs - particulary niCategory object to now accepts the newly introduced codes. 
Open API doc needed to be aligned with new codes that have now been introduced in MVC

UKPAY-3302: Update docs to support the new NI Category letters for FY2022-2023. (F, I, S, L, V)

---

xero_accounting.yaml

The previous sample for CreateContact didn't work
Have removed the contact id that isn't required for creating a contact
Original was based on the server response, so have also removed fields that shouldn't be on the request.

correct sample JSON for PUT Contacts

---

xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

Resolves XeroAPI/Xero-OpenAPI#484
This did at least successfully generate into java with the command:
```sh
docker run --rm -v $PWD:/local openapitools/openapi-generator-cli:v4.2.0 generate -i /local/xero_accounting.yaml -g java -o /local/out/java
```
it seems having multiple paths that differ only in their parameter types is accepted by the generator so long as they have different `operationId` fields?

Add getJournalByNumber call

---

xero-payroll-au.yaml

Add `Paid Parental Leave` and `Workers Compensation` earnings types to the payroll AU SDK in preparation for the implementation in the API itself.
Add EarningsType enum value `PAIDPARENTALLEAVE` and `WORKERSCOMPENSATION` to the Payroll AU SDK spec

Add Paid Parental Leave and Workers Compensation to earnings types

---

.gitignore
xero-payroll-au.yaml

Update the AU payroll config to allow support for paid leave categorization. This includes adding two new properties to the `LeaveType` object.
_Abbreviations_
- STP: Single Touch Payroll
- SGC: Superannuation Guarantee Contribution
Additions to `xero-payroll-au.yaml`:
- Add new properties to the `LeaveType` object: `LeaveCategoryCode` and `SGCExempt` (See [docs](https://developer.xero.com/documentation/api/payrollau/payitems#get-payitems--elements-for-leavetypes))
- Add new schema definitions:
- `LeaveCategoryCode` enum 
- API consumers will need to categorize all leave pay items as part of STP phase 2. The leave category code will be used to determine which category a new leave pay item will be filed as.
- There are different rules for pay items created with these leave categories, some …

Add paid leave categorization support for AU payroll

---

xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

- added missing report tax types to the enum (CAPEXINPUT, UNDEFINED, CAPEXOUTPUT, ZEROEXPOUTPUT, GOODSIMPORT, NONEINPUT, NOTREPORTED)
Resolves [Issue 430](https://github.com/XeroAPI/Xero-NetStandard/issues/430)

Add missing report tax type codes

---

xero_accounting.yaml

Slight change in wording on `LineItem` is needed to cater for `DiscountRate` as well as `DiscountAmount`. 
Goes with [this ](https://github.com/XeroAPI/Xero-OpenAPI/pull/518)PR, previously approved and merged
This change needs to be released on the **31st October**
https://xero.atlassian.net/browse/INVINP-10104

[INVINP-10104] LineAmount wording change

---

xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

Updates `CreateBrandingThemePaymentServices` method to accept an array of `PaymentService` objects instead of just one `PaymentService` object to match API functionality
Resolves [Xero-Node #605](https://github.com/XeroAPI/xero-node/issues/605)
This will result in a small breaking change where any projects currently using this method will need to wrap their `PaymentService` object in a `PaymentServices` object like so:
`
{
"PaymentServices": [
{
"PaymentServiceID": "54b3b4f6-0443-4fba-bcd1-61ec0c35ca55",
"PaymentServiceName": "PayUpNow",
"PaymentServiceUrl": "https://www.payupnow.com/",
"PaymentServiceType": "Custom",
"PayNowText": "Time To Pay"
}
]
}
`

update createbrandingthemepaymentservices method and bump version

---

xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

- Updated data type of `IsReconciled` property of `BatchPayment` to boolean. 
- Updated data type of `TotalAmount` property of `BatchPayment` to decimal
Related to [this issue](https://github.com/XeroAPI/Xero-NetStandard/issues/453)
- Data types did not align with data returned by Accounting API.

Corrected datatypes of BatchPayment model 

---

xero-app-store.yaml

Add new vendor tag so Java SDK will properly parse date format
Xero-Java SDK is currently defaulting the date-time fields to DateTimeOffset. The App Store API actually returns dates in UTC with no offset. This vendor tag will change these fields to the correct type, LocalDateTime.
This fixes a serialization issue in the Xero-Java SDK

add x-is-datetime tag so Java SDK will use LocalDatetime

---

xero-payroll-au.yaml

Adding AllowanceContributesToAnnualLeaveRate, AllowanceContributesToOvertimeRate booleans for pay items
As part of STP2, two new checkboxes were added for allowance pay items - https://xero.atlassian.net/browse/AUP-8603.
- Jira: https://xero.atlassian.net/browse/AUP-8815
- Adding AllowanceContributesToAnnualLeaveRate and AllowanceContributesToOvertimeRate booleans to the Payroll AU SDK spec

AUP-8815: Update AU Payroll SDK allowance booleans

---

xero-payroll-au.yaml

Update the AU Payroll configuration to allow support for Cashed Out Leave.
This includes adding a new property to both the `LeaveApplication` object for leave requests, and `LeaveEarningsLine` object for pay slip identification.
Additions to `xero-payroll-au.yaml`:
Add new property `PayOutType` to the `LeaveApplication` object.
Add an equivalent property to the `LeaveEarningsLine` object.
API users need to be able to create Cashed Out Leave applications, and also to be able to tell which lines on the employee payslip corresponds to cashed out leave.

Add cashed out leave support for AU Payroll

---

xero-payroll-au.yaml

New endpoints added for expanding Leave functionality for AU Payroll
* LeaveApplications/v2 GET includes REQUESTED and REJECTED leave applications
* LeaveApplications/{id}/approve allows for approval of REQUESTED leave applications
* LeaveApplications/{id}/reject allows for rejection of REQUESTED or SCHEDULED leave applications
Added detail to LeaveApplications POST example to indicate expected inclusion of other attributes
Expanded functionality to allow for more comprehensive use of API for leave management

Add LeaveApplications/v2 and approve/reject for AU

---

xero_files.yaml

OpenAPI spec has paging info for Associations/objectid
Paging information has been added to the OpenAPI spec on the associations/{objectid} endpoint
The endpoint was updated and the Open API spec needs to be updated to reflect the new functionality
https://xero.atlassian.net/browse/APIB-4282

[APIB-4282] OpenAPI spec has paging info for Associations/objectid

---

xero_accounting.yaml

Added additional ReportTaxType used within the new Auto Sales Tax feature in the US edition of Xero
New sales tax functionality for US Xero organisations has resulted in a new ReportTaxType to be used. 
- [ x ] New feature (non-breaking change that adds functionality)

Added additional ReportTaxType - USSALESTAX

---

xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

This change is to remove empty enum values from the specifications of Accounting, Bankfeeds, Payroll_AU, and Projects.
The empty enum values use a reserved keyword name in PHP which causes errors while utilising the SDK. Issue reported at xero-php-oauth2 [#258](https://github.com/XeroAPI/xero-php-oauth2/issues/258)

Remove empty enum values from specs

---

xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

Recently introduced `idempotencyKey` for POST, PUT and PATCH requests broke existing invocations, as this optional parameter is added in between of the method definition instead of the end.
Previous: 
```
updateOrCreateInvoices (xeroTenantId: string, invoices: Invoices, idempotencyKey?: string, summarizeErrors?: boolean, unitdp?: number, options: {headers: {[name: string]: string}} = {headers: {}})
```
Now:
```
updateOrCreateInvoices (xeroTenantId: string, invoices: Invoices, summarizeErrors?: boolean, unitdp?: number, idempotencyKey?: string, options: {headers: {[name: string]: string}} = {headers: {}})
```
* Update method definitions to position `idempotencyKey` as last optional parameter.
* Fix method definitions where required request-body parameters are declared as optional.
* Below …

PETOSS-345 - Fix the Idempotency key order in method definitions

---

xero_accounting.yaml

It's reported by users (see CX0014522641 CX ticket) that the TaxType query param is not working. This query param is not supported by the Accounting API. What is supported is record filtering which allows users to append the `TaxType` in the endpoint's URL to filter for TaxRate with specific TaxType.
Does not work -> `/TaxRates?TaxType={TaxType}`
Works -> `/TaxRates/{TaxType}`
* Remove the declaration of `TaxType` query param in GET TaxRates
* Add a new spec for `TaxRates/{TaxTypes}`
We need to make this change to avoid confusing users since I few have used `TaxType` as query param.

Update GET TaxRates spec

---

xero-payroll-au.yaml

This change is just to remove the `JOBKEEPER` value from our allowance type enum collection. This is because this item is now deprecated and should no longer be used by API consumers.
The JobKeeper allowance type was developed to be used within the period of time when the JobKeeper covid19 program was running. Now that the government program has ended, it is being removed from Xero. This change is to remove the allowance type from our API to prevent users of our API from using this now deprecated item.

AUP-14336 Removing JobKeeper allowance type

---

xero_accounting.yaml

Add tax types and report tax types for Disallowed Expenses tax rates in the Singapore region.
New tax rates are being introduced for compliance reasons

[STA-948] Add disallowed expenses

---

xero_files.yaml

Added 'Name', 'Size', 'SendWithObject' to object association endpoint
Adding these 3 new properties to response of an existing /associations/{objectId} endpoint
https://xero.atlassian.net/browse/XBFIL-4328
Adding these 3 new properties to response of an existing /associations/{objectId} endpoint as requested by another internal team.

XBFIL-4328- Fix formatting and add 3 new fields

---

xero-payroll-nz.yaml

The `openapi` version number in the Xero Payroll NZ spec is currently incorrect which can prevent code generation from succeeding. This change corrects the version.
Ensures the Xero Payroll NZ `openapi` version is of a valid format.
N/A

Fix incorrect openapi version in Xero Payroll NZ spec

---

xero_accounting.yaml

This PR adds the `PageInfo` object to the HTTP response for these endpoints:
- payments
- purchase Orders
- contacts
- credit notes
- manual journals
- invoices
- bank transactions
- pre payments
- over payments

[APIB-5555] Adds pagination information to select API.Accounting endpoints

---

xero_accounting.yaml

Introducing Search Term in GET invoice endpoint.
SearchTerm added to GET invoice endpoint
Aligning OpenAPI spec to existing functionality by introducing SearchTerm as a query string.

Add search term component to GET invoice endpoint

---

xero_accounting.yaml

As part of this [previous PR](https://github.com/XeroAPI/Xero-OpenAPI/pull/595), we need to add the same query parameter for `GET /Overpayments` and `GET /Prepayments` endpoints.

[APIB-5518] Adds the pageSize query parameter

---

xero_accounting.yaml

The debit lines should be positive and credits negative in the code examples for creating and updating journals
Changed the signs so that they are correct
If the examples were followed exactly the journal would be the wrong way round
- [X ] Bug fix (non-breaking change that fixes an issue)

Update xero_accounting.yaml to change signs for debit and credit

---

xero_accounting.yaml

Add threshold Warnings object to responses
Currently Warnings object is returned from the public API but not SDKs. Adding this object into the SDK response to align with the public doc and public API.

[APIB-5670] Add threshold Warnings to responses

---

xero-payroll-uk.yaml

PETOSS 579 | Adding Default parameter value to createEmployeeLeaveType

---

xero_accounting.yaml

- Added USST fields to the Invoices and Credit Notes endpoints:
- InvoiceAddresses
- SalesTaxCodeId
- Taxability
- TaxBreakdown
- The Invoices and Credit Notes endpoints are going to return some new fields related to USST.

[UST-4371] Add USST fields to Invoices and Credit Notes endpoints

---

xero-payroll-nz.yaml

Based on this notice [Payroll NZ Holiday Act (2003) Update]( https://developer.xero.com/documentation/api/changelog/payrollnz-holiday-act), Add the following fields to the following objects:
- Period / Employees Leave Periods - https://developer.xero.com/documentation/api/payrollnz/employeeleaveperiods
- NumberOfUnitsTaken (GET)
- TypeOfUnits (GET)
- TypeOfUnitsTaken (GET)
- PeriodStatus will now always return “Estimated”
- Employees Leave Setup - https://developer.xero.com/documentation/api/payrollnz/employeeleavesetup
- Deprecated
- SickLeaveHoursToAccrueAnnually (POST)
- SickLeaveMaximumHoursToAccrue (POST)
- New
- SickLeaveToAccrueAnnually (POST)
- replaces SickLeaveHoursToAccrueAnnually
- SickLeaveMaximumToAccrue (POST)
- replaces SickLeaveMaximumHoursToAccrue
- …

NZP-4591 Add new fields and deprecations for NZ Holidays Act

---

xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

- Following[ Cash Validation - fix bug for data source classification](https://xero.atlassian.net/jira/software/c/projects/LEND/boards/4170?selectedIssue=LEND-2862) implemented on June 20, 2024, this is the 2nd release to remove indirectBankFeed data point from the Cash Validation schema. We want to roll out this change at Feb 3, 2025
- Add new fields and deprecations for NZ Holidays Act

OAS version update - 7.0.0

---

xero-payroll-uk.yaml

- Added entities for NICategoryLetter and NICategory.
- Freeport and Investment zone NI category letters added.
- Updated Employee entity. NICategoryLetter has been marked as deprecated and NICategories added as a new property.
- Validation added to NICategory entity. Validation added for `workplacePostcode` and `dateFirstEmployedAsCivilian`.
- Updated Employment POST. Added NI Categories and removed deprecated `niCategory` property.
- GET Employee 200 response example updated and NI Categories added.
- Added missing comma to Employee POST success response example.
This change reflects the current functionality available in the public API and as shown in Xero documentation. 
[GET Employee](https://developer.xero.com/documentation/api/payrolluk/employees#get-employees)
[POST …

Ni category updates

---

xero-payroll-uk.yaml

- Add missing leave type to the EmployeeStatutoryLeaveBalance and EmployeeStatutoryLeaveSummary responses for UK. 
- This leave type has been supported by these endpoints for the last two years, but they were not added when the work was done.

feat: Adding Bereavement enum to EmployeeStatutoryLeaveBalance and EmployeeStatutoryLeaveSummary for UK

---

xero_accounting.yaml

Adding support for a previously unseen OrganisationRole on the Users and ExpenseClaim endpoints.
ExpenseClaims and Users endpoints return a previously unseen role. Adding the new role so that server response can be handled by our SDKs

Add missing OrganisationRole REMOVED

---

xero-payroll-uk.yaml

- Add new leave type to the EmployeeStatutoryLeaveBalance and EmployeeStatutoryLeaveSummary responses for UK.
- We introduced Neonatal Care Leave recently and these endpoints will in the future (in the case of balance) and have (in the case of summary) support for neonatal care

[UKPAY-11962] feat: Adding NeonatalCare enum to EmployeeStatutoryLeaveBalance and EmployeeStatutoryLeaveSummary for UK

---

xero_accounting.yaml

- The **Date** field of the payment is returned as "\/Date(1721347200000+0000)\/" from API but [document ](https://developer.xero.com/documentation/api/accounting/payments#get-payments) says it is 2024-07-19 
- This PR is to update description of Date field for Payment and BatchPayment endpoint
- This is a bug fix aimed at preventing customer confusion. It allows them to perform necessary data conversions beforehand if their receiving system expects a different date format (e.g., SQL expecting a standard date string).

[XBAP-22591] - Updated Date field decsription for Payment and Batchpayment endpoint

---

xero_accounting.yaml

- Mark Accounting API Employee endpoints as deprecated
- Mark endpoints as deprecated
- Add description to indicate date when removal of endpoints will occur
The Accounting API Employee endpoints will be removed on April 28, 2026.
These endpoints are related to Employees used for the Pay Run feature, which is being retired. See [Xero Central article](https://central.xero.com/s/article/About-the-retirement-of-pay-run) for more information.
- Users making use of the Pay Run feature have already been notified
- Developers making use of these endpoints have been identified and will be notified in the coming days.

Mark Accounting API Employee endpoints as deprecated

---

.github/workflows/spectral-lint.yml
validator/scripts/validate-all.sh
validator/spectral.yaml
validator/xero-spectral.yaml

This PR is to introduce OpenAPI specification validation for all OpenAPI Spec files (`xero*.yaml`)
Using the open source tool [Spectral](https://stoplight.io/open-source/spectral) to validate OpenAPI Specification files to well known standards (with minimal customisations).
This change does not alter any Open API Specifications, however there is an issue raised [here](https://github.com/XeroAPI/Xero-OpenAPI/issues/741) which would require a minimal type change to the response code only for one API spec.  We could then add `xero-finance.yaml` to the files validated in `validate-all.sh`
The ruleset extends the default using `xero-spectral.yaml` to make allowances for our current state of Open API specs, and can be improved upon in future PRs.
* Ensure all OpenAPI spec files are named …

Introduce spectral OpenAPI spec linting

---

validator/scripts/validate-all.sh
xero-app-store.yaml
xero-finance.yaml
xero-identity.yaml
xero-payroll-au.yaml
xero-payroll-nz.yaml
xero-payroll-uk.yaml
xero-projects.yaml
xero_accounting.yaml
xero_assets.yaml
xero_bankfeeds.yaml
xero_files.yaml

Fix a failing validation on Open API Specification for the `xero-finance.yaml` file.
Issue: https://github.com/XeroAPI/Xero-OpenAPI/issues/741
Response codes should be `string` not `numeric`.
N/A

fix: xero-finance.yaml responses numeric to string

---

xero_accounting.yaml

Adding a TaxNumberType for Contacts
Adding a TaxNumberType for Contacts
Added TaxNumberType to match the public developer docs https://developer.xero.com/documentation/api/accounting/contacts

[SAS-559] Add TaxNumberType for Contacts
