accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
Adding a couple of fields introduced in recent API releases
=> Adding logoUrl and AddToWatchlist fields

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
Added extra ReportTaxType 'EXEMPTCAPITAL' as returned in the AU Demo Company
=> Adding ReportTaxType Enum

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
arguments didn't match what is in the documentation
=> Update arguments for BankSummary report

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
For node template to ensure the JSON requestBody is properly handled even though an empty response (void) is returned.
=> Add vendor extension for 204 response

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
ADD QUOTES methods
createQuotes
updateOrCreateQuotes
getQuoteHistory
createQuoteHistory
Polish up the Quote object
=> Added Quotes

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
Modify the example request body for use in node documentation
Turn unitdp into parameter componenet
=> Update example request Bodies

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
Add back example of single GetHistory Record for Java Unit tests
Fix example create Item request body for node documentation
=> Add TrackingOptionId for lineitems on Quotes

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
Abstracted If-Modified-Since into a shared compenent
Update Order param example
Update Where clasue examples
Update some requestBody examples
Remove required attribute ReportTaxType from TaxRate
=> Get param updates and examples for node docs

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
Added to the following ..
BankTransactions
- getBankTransaction
- createBankTransactions
- updateBankTransaction
- updateOrCreate
CreditNotes
- getCreditNotes
- createCreditNotes
- updateCreditNote
- updateOrCreateCreditNotes
Invoices
- getInvoice
- createInvoices
- updateInvoice
- updateOrCreateInvoices
Items
- getItem
- createItems
- updateItem
- updateOrCreateItems
Receipts
- getReceipts
- getReceipt
- createReceipt
- updateReceipt
=> Added missing unit decimal point param

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
Thanks to @lukesawyer's PR in .NET SDK, we have discovered a missing enum of "NONE" for SalesTaxPeriod of organisation object. 
Steps to recreate on an AU org, under financial setting of the org setting: 
An example of the object: 
```
<Organisation>
<Name>A Demo Company (AU) Jenks</Name>
<LegalName>A Demo Company (AU) Jenks</LegalName>
<PaysTax>true</PaysTax>
<Version>AU</Version>
<OrganisationType>COMPANY</OrganisationType>
<BaseCurrency>AUD</BaseCurrency>
<CountryCode>AU</CountryCode>
<IsDemoCompany>true</IsDemoCompany>
<OrganisationStatus>ACTIVE</OrganisationStatus>
<RegistrationNumber>11111111138</RegistrationNumber>
<TaxNumber>xxxxxxxx616</TaxNumber>
<FinancialYearEndDay>30</FinancialYearEndDay>
<FinancialYearEndMonth>6</FinancialYearEndMonth>
<SalesTaxBasis>ACCRUALS</SalesTaxBasis> …
```
=> Added SalesTaxPeriod NONE to organisation object

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml, assets-yaml/Xero_assets_1.0.0_swagger.yaml, bankfeeds-yaml/Xero_bankfeeds_1.0.0_swagger.yaml, identity-yaml/Xero-identity-1.0.0-swagger.yaml, payroll-au-yaml/Xero-payroll-au-1.0.0-swagger.yaml, projects-yaml/Xero-projects-1.0.0-swagger.yaml
bump version of all specs to 2.0.0
=> Clean up info & server details

accounting-yaml/Xero_accounting_2.0.0_swagger.yaml
Added the tax rates returned for a Singapore organisation.
=> Added Singapore TaxRates and ReportTaxRates

accounting-yaml/xero_accounting.yaml
Quotes can be retrieved in PDF format, this should add the ability. 
Section copied and pasted from the similar getInvoiceAsPdf function.
=> Add getQuotesAsPDF

assets-yaml/xero_assets.yaml
Seeing if this trickles down to successful generation of the expected enum for `getAssets`
@SidneyAllen - you mentioned maybe doing it with Refs from another point?
=> enums capitalized for assets api

accounting-yaml/xero_accounting.yaml
Can not add this attributes until all SDKs can support vendor extension - but ready to uncomment
=> Comment out x-is-msdate and x-is-msdate-time

accounting-yaml/xero_accounting.yaml
x-is-msdate-time-temp: true
x-is-msdate-temp: true
This will allow for development of python SDK without impacting other SDKs until we are ready to remove the format: date and format: date-time
=> Added temporary vendor extensions for MS Date in Accounting

accounting-yaml/xero_accounting.yaml
IncludeOnline should be at the end of the path being called
xxxxxxxxxx?IncludeOnline=true, however it was being included like xxxxxxxx/IncludeOnline
This should correct that.
=> Correct the IncludeOnline value so that it is a query parameter and not included directly in path

assets-yaml/xero_assets.yaml
=> Asset yaml update

payroll-au-yaml/xero-payroll-au.yaml
@SidneyAllen 
This parameter AllowanceType  gets passed-back when getting PayItems, some type of the pay item is created in Xero. In other EarningRates, it is not always there or set to null.  
example response: 
```json
{
"Id": "a4b0a82a-6d8e-48c8-ad7d-11806b302433",
"Status": "OK",
"ProviderName": "Jenks Postman OAuth2.0",
"DateTimeUTC": "/Date(1587216597016)/",
"PayItems": {
"EarningsRates": [
{
"EarningsRateID": "e45034b7-674e-4bb0-8163-5d19dab167b8",
"Name": "Ordinary Hours",
"EarningsType": "ORDINARYTIMEEARNINGS",
"RateType": "RATEPERUNIT",
"AccountCode": "477",
"TypeOfUnits": "Hours",
"IsExemptFromTax": false,
"IsExemptFromSuper": false,
"IsReportableAsW1": false,
"UpdatedDateUTC": "/Date(1571357549000+0000)/",
"CurrentRecord": true
},
{
"EarningsRateID": …
```
=> Added new property and list of enum for EarningRate

accounting-yaml/xero_accounting.yaml
=> Added UK Domestic Reverse Charge VAT rates

accounting-yaml/xero_accounting.yaml
Found by community member: https://github.com/XeroAPI/xero-node/issues/412
A deserialization is being effected for node sdk.. I can fix in the SDK itself, but this seems like an API wide type fix that should propagate through all sdks?
=> journal number, from string to number

accounting-yaml/xero_accounting.yaml
=> Add "Page" parameter to payments endpoint

payroll-au-yaml/xero-payroll-au.yaml
AU PAYROLL
PayItem
- AccrueLeave change from number to boolean
LeaveType
- NormalEntitlement change from Int to Double
=> Add PayItem example req/response in AU Payroll

accounting-yaml/xero_accounting.yaml
Remove style:simple property from Statuses Filter
Change getQuoteAsPDF method to use QuoteID is path not QuotesID
=> Fix Accounting API

accounting-yaml/xero_accounting.yaml, assets-yaml/xero_assets.yaml, bankfeeds-yaml/xero_bankfeeds.yaml, identity-yaml/xero-identity.yaml, payroll-au-yaml/xero-payroll-au.yaml, payroll-uk-yaml/xero-payroll-uk.yaml, projects-yaml/Xero-projects.yaml
Employee object
Remove HomeAddress as required property
Add Account Type enum WAGESPAYABLELIABILITY
=> AU Payroll updates

payroll-uk-yaml/xero-payroll-uk.yaml
Change method getPayslips to getPaySlips
Add missing earningsRates
Add missing deduction type enums
Add missing deductible category enums
=> UK Payroll  updates for python

payroll-uk-yaml/xero-payroll-uk.yaml
=> remove duplicate deduction enum

payroll-au-yaml/xero-payroll-au.yaml
AnnualNumberOfUnits
FullTimeNumberOfUnitsPerPeriod
=> Add missing properties from LeaveLine

xero_accounting.yaml
PR for adding Open API specs for the new organisation e/p sub-resource
=> Add specs for the new org endpoint subresource

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> bump version

xero_accounting.yaml
Validated the setup endpoint and related components.
Further separated schema components into discrete new components
The setup endpoint was not functional
With the caveat that this endpoint was only added in the last two weeks and the setup endpoint is rarely used.  I would not see this change as necessitate a major version release for SDKs.
=> Setup endpoint refactor

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> increment version

xero-payroll-nz.yaml
Modifications to NZ payroll when validated against python sdk
=> NZ payroll improvements

xero-payroll-uk.yaml
Add missing employer tax line on payslip object
=> UK Payroll add missing employer tax lines

xero_accounting.yaml
Reverts XeroAPI/Xero-OpenAPI#319
=> Revert "Add DueDate to CreditNotes"

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Modify the accounting spec
BatchPayment - reference maxlength changed from 12 to 255
CreditNote - add DueDate property
=> Sid development

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Due to breaking changes increment the minor version.
NZ PAYROLL
- In TaxSettings changed periodunits from int to decimal
- Move CalendarType into a separate component for reuse by PayRun and PayRunCalendar
- Add TwiceMonthly value to CalendarType enum
=> Bump to 2.6.0

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Remove maxlength from Invoice reference
bump version to 2.6.1
=> Remove maxlength from Invoice reference

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Address component will be used by Contact and the DELIVERY enum was removed from AddressType
AddressForOrganisation added for use in the Organisation object.
=> Split Address componenet into 2 instances

xero-payroll-au.yaml
LUMPSUME
An extra EarningType is being returned from the API
This allows the SDK to handle the new type
=> added extra Earnings type

xero_bankfeeds.yaml
There are a number of possible error types described on the following two pages that were not implemented in the Bankfeeds Error.type enum. Added these values to the enum. 
https://developer.xero.com/documentation/bank-feeds-api/feed-connections-errors
https://developer.xero.com/documentation/bank-feeds-api/statements-errors
=> Add missing values from docs into Bankfeeds Error.type enum

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Bump version 2.8.1

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Add readOnly property to BrandingTheme on Contact object
=> Readonly BrandingTheme

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Fix general content issues in preparation for our repo to consume and publish this in the devportal
Fix general content issues (spelling errors, capitalisation consistency, invalid guids, summary content etc.)
No changes in terms of actual structure, just content :)
As we are going to publish our public api reference using this repo in the near future, we need to fix any content related issues that may appear in the page (spellings, consistent text etc.)
- [x ] Bug fix (non-breaking change that fixes an issue)
=> Dca 148 content fix

xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Fix general content issues in preparation for our repo to consume and publish this in the devportal
This is same PR as DCA-148-Content-Fix, except all capitalisation for accounting-api endpoints have been reverted
Fix general content issues (spelling errors, capitalisation consistency, invalid guids, summary content etc.)
No changes in terms of actual structure, just content :)
As we are going to publish our public api reference using this repo in the near future, we need to fix any content related issues that may appear in the page (spellings, consistent text etc.)
- [/ ] Bug fix (non-breaking change that fixes an issue)
=> DCA-148 Revert Capitalisation

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
In preparation for use to generate API reference documentation, we've done some clean up of misspellings, add more consistency around summaries and descriptions.  Adjusted capitalisations on paths.
=> Clean up of summaries, descriptions and capitalization

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
2.8.5 was deleted previously, so can't be reused.
=> Bump to 2.8.6

xero_accounting.yaml
=> Add Warnings array to CreditNote object

xero_accounting.yaml
This endpoint previously used the singular CISOrgSetting component, but that did not match the API response.
Create a new CISOrgSettings model with a CISSettings property (array of CISOrgSetting) that matches the API response.
=> Add CISOrgSettings component for use in GET Organisation/CISSettings

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> bump version to 2.9.0

xero_files.yaml
Debugging files API for node api generation
A useful attribute to have in form generation Used to demark if an API uses the multipart form data http post type
Make all `FileID` capitalized so that the replacement on the URL matches.
=> Files API updates WIP

xero_accounting.yaml
=> Add BatchPaymentID to Payment object

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> bump version to 2.9.2

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Performed audit of all operations in the Files API spec
Standardized IDs in path and parameters
Corrected Response codes where needed from 200 to 201.
Corrected responses object for 204 - should be none (void)
Added example requests and responses
=> Files API clean up and validation

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Add missing enums from UK Payroll

xero_accounting.yaml
This PR does not impact the SDK clients, only the SDK reference docs.  Therefore, I won't be versioning the specifications at this time.
=> Meta data improvements for NodeJS SDK documentation generation

xero_accounting.yaml
=> Add csharp property on x-examples for date/time

xero_accounting.yaml
=> More updates to SDK reference doc generation

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Bump version to 2.9.5

xero_accounting.yaml
=> Reworking lineitems for x-example meta data

xero_accounting.yaml
=> update x-example lineitems

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
FILES API
Add new method to Files so new uploads go into a specific folder
Remove the FolderId parameter from the UploadFile method as those files always go into the inbox.
NZ PAYROLL
Add "history" as a valid status to SalaryAndWage object
Add "Requested" as a valid status to Timesheet object
=> Files and NZ Payroll updates

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Fix path for uploadFileToFolder method
Also, replace inline objects with UploadObject for use by both upload methods
=> Fix path for uploadFileToFolder method

xero_accounting.yaml
=> Working through x-snake example for python SDK docs

xero_accounting.yaml
=> Add x-snake for SDK doc generation

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> bump version to 2.10.4

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Make CalculationType optional on deduction line
=> AU Payroll DeductionLine issue

xero_bankfeeds.yaml
Update bankfeeds spec to include missing error
=> Update Bankfeeds spec with missing error

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Add summaryOnly param to getContacts operation

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Add payments array to Prepayment object

xero_accounting.yaml
Have added the summaryOnly param details for Contacts and Invoices endpoint
Adding newly created param to the specs
=> Adding SummaryOnly param to contacts and invoices

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Bump minor version to 2.12.0

README.md
Removes extraneous lines from README.md
=> Removes extraneous lines from README.md

xero_files.yaml
- Added metadata to the xero_files.yaml file to support documentation generation. 
- Changed the default UUIDs to "00000000-0000-0000-0000-000000000000" for consistency with the Accounting API.
=> Added metadata for Files API documentation

xero_assets.yaml, xero_files.yaml
- Added metadata to the xero_assets.yaml file to support documentation generation. 
- Changed the default UUIDs to "00000000-0000-0000-0000-000000000000" for consistency with the Accounting API.
=> Added metadata for Assets API documentation

xero-payroll-uk.yaml
Added x-examples for runnable code samples in the generated docs for Payroll UK.
- [x ] New feature (non-breaking change that adds functionality)
=> Added x-examples for Payroll UK

xero-payroll-nz.yaml
Added x-examples for runnable code samples in the generated docs for Payroll NZ.
- [x ] New feature (non-breaking change that adds functionality)
=> Added metadata to support docs generation for Payroll NZ

xero-payroll-au.yaml
Added x-examples for runnable code samples in the generated docs.
- [x ] New feature (non-breaking change that adds functionality)
=> Added metadata to support docs generation

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Bumping payroll docs and specs across the board for recent budgets and docs code
=> bump version for payroll docs

xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml
There were a few edge cases around objects not building right.
WIP pr for code review of the generated docs bugs.
=> Fixes for bugs in the display of the SDK docs

xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml
Big cleanup for consistency of examples with accounting api - no functional changes just elements that will clean up the SDK doc gen
=> Payroll doc generation bug bashing + projects spec cleanup

xero-identity.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Just a version bump to match the release notes that encapsulated the previous PR's budgets fixes.
=> bump version to reflect last release semver

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Semver bump to include Reference date in AU payroll
> https://github.com/XeroAPI/Xero-OpenAPI/commit/fc6865aa42cfdea3b482df030be4d592ba7b2797
Customer reported bug from API CX
=> get all OAS versions synced. Add reference date to AU payroll

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Bump version for adding BankAmount
=> bump version for adding bankamount

xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Fixes the OAuth2 scopes to include any permission that works for the function.
Also a large audit of the previously non-functioning scopes.
=> Update scopes across all spec files to include all scopes that grant access to actions

xero-payroll-au.yaml
New field TerminationReason has been added at API level
Full detail on the field here:
https://developer.xero.com/documentation/api/payrollau/stp-changes/#termination-reason
=> Add extra employee field

xero-app-store.yml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Implements the endpoints available in Xero's API spec.
https://developer.xero.com/documentation/guides/how-to-guides/xero-app-store-subscriptions/
https://developer.xero.com/documentation/api/xero-app-store/subscriptions
Subscriptions endpoints enable you to query data about the users who have paid to subscribe to your application through Xero.
* adds `EASTERISLANDSTANDARDTIME`
=> App Store subscriptions specification

manifest.json, xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Initial release of the finance API specs
V2
The Finance API is a collection of endpoints which customers can use to give lenders the confidence they need to provide capital in the course of a loan application.
The Finance API is a closed API that is only available to those that have an established (usually, but not limited to, financial services) partnership with Xero.
If you're an existing partner that wants access, contact your local Partner Manager.
If you're a financial institution or other partner who wants to leverage the Finance API for your business customers, contact us to become a financial services partner.
The Finance API covers rich data points built bespoke for lending. Encompassing easy-to-use powerful raw data, as well as capability which may provide additional confidence …
=> Add finance yaml

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
bumps version number and adds missing `seatUnit` to `Product` schema
- [ x] Bug fix (non-breaking change that fixes an issue)
=> adds asb seat unit

xero-finance.yaml
Adds query examples for docs generation
This makes the generated sample code more useful. Instead of "startDate_example" it now reads "2021-09-15"
=> adds examples for queries

xero-finance.yaml
Changes to the text for Finance API, Accounting product.
Changes to the text for Finance API, to clarify Accounting product usage.
Clarification around usage.
https://xero.atlassian.net/browse/LEND-1955
=> [LEND-1955] updates to accounting api

xero-payroll-au.yaml
JIRA: https://xero.atlassian.net/browse/AUP-5483
Add API SDK Support for LumpSumW and SCHEDULE4MANUAL tax type
=> Add API SDK Support for LumpSumW and SCHEDULE4MANUAL tax type

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Adds vendor tags to finance spec necessary for xero-python SDK and language specific docs build
=> Adds finance spec vendor tags for python

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
bumps version and adds some missing vendor tags to accounting spec
Will improve language specific generated docs
=> bump version number and add vendor tags to accounting spec

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Adds `x-is-money` tag to Finance API spec
This is necessary for .NET and Ruby SDK generation
=> adds x-is-money tag to finance spec

xero-finance.yaml
Updates finance contacts example to be in line with API
No relevant changes for users
- [ x ] Bug fix (non-breaking change that fixes an issue)
=> fixed finance contacts example to use numeric account codes

xero_files.yaml
Files can be attached to Quotes, so I've added to the appropriate types on this endpoint for the associations between files and the Quotes
=> Added Quotes to files API

xero-app-store.yaml
=> adds status to subscription item and updates available enums

xero-payroll-au.yaml
* Adding Allowance Category
* Updating Allowance Type to include new STP-2 allowances
Updates are in relation to new STP-2 functionality. We are introducing an allowance category and we are updating the allowance type enum to include three new allowance types.
Two enums are updated: Allowance Category and Allowance Type. These fall part of our new STP-2 functionality.
- [ X] New feature (non-breaking change that adds functionality)
=> AUP-5767 - API SDK update for the new allowance types and Other allowance categories

xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Some fields were set to 'date-time' when they are really just 'date'. This leads to a parser error in the Java SDK so needed to be updated.
- [x ] Bug fix (non-breaking change that fixes an issue)
=> change some date-time fields to date based on actual response format

xero-finance.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_files.yaml
Updates spec files to support generating python docs
=> Xero python docs

xero-app-store.yaml
Adding metered capabilities for app store subscriptions end point
Update to the latest payload schema
=> Make changes to reflect Metered Billing

xero_accounting.yaml
Added a new organization class to `xero_accounting.yaml` for ultimate plan.
This is required by the ultimate plan rollout by the end of the month.
=> Add new organization class to xero_accounting.yaml

xero_accounting.yaml
Added new tax rate for Singapore: TXRCTSINPUT - Imported services attributable to taxable supplies
* Keep inline with Xero accounting application
=> [STA-336] added new tax rate for Singapore

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Project API
- Adds `CreateTask`, `UpdateTask`, and `DeleteTask` methods
=> Project tasks

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Added new endpoints for repeating invoice create.
=> Add repeating invoice create operations

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
This PR adds POST batchPayments. It enables deleting a batchPayment given the batchPaymentID. It also resolves [this issue](https://github.com/XeroAPI/Xero-OpenAPI/issues/499)
Added POST /BatchPayments and /BatchPayments/{BatchPaymentID}
This endpoint method has been missing from our spec.
=> add post batchPayments to accounting spec

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
1. Updated the version from 2.24.0 to 2.25.0 to 11 files
2. Added  HasLoanOrStudentDebt in the AU payroll
This was based off an issue raised by the Node SDK. 
Issue 575 in the Node SDK issues
=>  Adds missing tax declaration and updating version

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
This PR adds GET batchpayments/{batchPaymentID}. It enables getting a batchPayment give the batchPaymentID. 
Added GET /BatchPayments/{BatchPaymentID}
Resolves [this issue](https://github.com/XeroAPI/xero-node/issues/535).
=> add GET batchPayments/{batchPaymentID} to accounting spec

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Fixes Projects API `createTask` method to return object of type `Task` 
Resolves Xero-Node [#599](https://github.com/XeroAPI/xero-node/issues/599)
=> Fixes create task response type

xero_accounting.yaml
DiscountAmount now applies to Quotes too once LIG (Line Item Grid) goes live. This change goes hand in hand with the following 2 PR's and need to be released on the **31st October**
1. https://github.dev.xero.com/APIteam/DevX.TechnicalMarkdownDocumentation/pull/371
2. https://github.dev.xero.com/APIteam/Api.Transformer/pull/42
https://xero.atlassian.net/browse/INVINP-10104
I'm busy finalizing the new template as per the new process around API changes that is being trailed. See [here](https://xero.slack.com/archives/C046CD15C5A/p1666229260959719)
=> [INVINP-10104] Add DiscountAmount for Quotes

xero-app-store.yaml
Add in usage/metered api end points for app store.
There has been a few changes internally which is missing on here 
Source: https://developer.xero.com/documentation/api/xero-app-store/metered-billing
Aligns more with the new metered billing feature
=> Appstore billing usage end points

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Added BatchPayment property to Payment component.
Batchpayment component is provided from API via GetPayments endpoint. This property was not present in the payment data model. 
Changes relate to this [issue 449](https://github.com/XeroAPI/Xero-NetStandard/issues/449)
Expose BatchPayment property in Payment model.
=> Added BatchPayment property to Payment component

xero_accounting.yaml
Add 2023 tax rates for Singapore
- Keep inline with Xero accounting application
=> [STA-495] Create tax rates for 2023 Open API

xero-app-store.yaml
There is no timezone information in the output so I'm removing it to reduce confusion
Removal of "Z" in example payloads
More accurately represent payload
~- [ ] New feature (non-breaking change that adds functionality)~
~- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)~
=> Correct Timezone suffix in examples as it's not what the API produces

xero-payroll-uk.yaml
Update the case in `BackPay` property of `earningsType`
Resolves [Xero-Ruby #241](https://github.com/XeroAPI/xero-ruby/issues/241)
- Argument Error invalid value for earnings_type
=> Update xero-payroll-uk.yaml for EarningsType

xero_files.yaml
Add Files Api /Association/Count endpoint
Add Files Api /Association/Count endpoint. It allows developers to fetch a count of associations for a list of objects.
See description. Previously, developers had to call this for each object.
=> INVINP-10767 Add /Association/Count endpoint

xero-payroll-au.yaml
- Add definition for OpeningBalance PaidLeaveEarnings
- PaidLeaveEarnings is a new type of OpeningBalance that will be supported in the near future.
=> AUP-9467: Add definitions for OpeningBalance PaidLeaveEarnings

xero_accounting.yaml
Fix existing reverse charge codes too
Add 2023 Reverse Charge tax rates for Singapore
Keep inline with Xero accounting application
https://xero.atlassian.net/browse/STA-757
=> [STA-757] Add Reverse Charge Singapore Y23

xero_accounting.yaml
=> [STA-874] Create compliance tax rates in XeroApi

xero-finance.yaml
As Cash Validation Api has now rate limiting, there is a new response type added to reflect that.
=> Adding a new response type for rate limiting

xero_accounting.yaml
Adds the deletion of allocations to Credit Notes, Prepayments and Overpayments
- Adds the Allocation ID in the GET requests for Allocations of Credit Notes, Prepayments and Overpayments.
New features.
N/A
=> INVINP-11482 Delete allocations

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Removed random character in getPurchaseOrderAttachmentByFileName
Added two new enum values in LeavePeriodStatus:
=> bump version and fix two issues

xero_accounting.yaml
Remove the Contact's SkypeUserName field, from the API.Accouting Contact's endpoints. ([BPC-7036](https://xero.atlassian.net/browse/BPC-7036))
[BPC-7036]: https://xero.atlassian.net/browse/BPC-7036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BPC-7036] - Remove Contact's  SkypeUserName field.

xero_accounting.yaml
Updated 1099 report sample JSON response.
1. Updated documentation for 1099 report.
=> USTNN-2546 Updated 1099 report open-api documentation

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Added the optional idempotency-key header param to all PUT, POST, and PATCH requests.
You can read more about how this param is supported [here](https://developer.xero.com/documentation/guides/idempotent-requests/idempotency/).
=> add support for idempotency-key

xero_accounting.yaml
- Add 9% tax rates for Singapore
- Compliance with new IRAS GST rate of 9% starting 2024
=> [STA-905] added 9% tax rates for Singapore

xero-payroll-nz.yaml
Added new property on the employee object: jobTitle
New field now returned on the NZ Payroll employee endpoint 
- [x ] New feature (non-breaking change that adds functionality)
=> Update xero-payroll-nz.yaml to include new property in the employee object

xero-payroll-au.yaml
This reverts commit f4ea250997a6ec4c7a7bff933e68f167ce4caf96.
Reverted commit id f4ea250997a6ec4c7a7bff933e68f167ce4caf96
=> Revert "AUP-14336 Removing JobKeeper allowance type"

xero-payroll-au.yaml
=> Removes JobKeeper enum again

xero_accounting.yaml
Introducing new organisation classes
New classes have been introduced:
- Ignite
- Grow
- Comprehensive
In order to comply with upcoming changes to packages, new organisation classes need to be introduced.
=> Update xero_accounting.yaml with new organisation classes

xero-finance.yaml
There was a [bug fix](https://github.com/xero-internal/CreditIntegrations.CashValidation.Api/pull/179/files) for Statement data sources in Cash Validation Api which already released, This PR is to update the descriptions on  DataSourceResponse model.
Describes the purpose of each field in DataSourceResponse to be align with the [bug fix](https://github.com/xero-internal/CreditIntegrations.CashValidation.Api/pull/179/files).
=> [LEND-2862] update data source descriptions

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> OAS version update 5.0.0

xero_accounting.yaml
=> [APIB-5555] Use the correct ref for GetInvoicesResponse

xero_accounting.yaml
Reverting this PR https://github.com/XeroAPI/Xero-OpenAPI/pull/597
=> [APIB-5560] Revert pagination information

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> OAS version update 5.0.1

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> OAS version update to 6.0.0

xero_accounting.yaml
Add the remaining ultimate sub-plans.
Add the remaining ultimate sub-plans.
ULTIMATE subplans are included:
- ULTIMATE_10
- ULTIMATE_20
- ULTIMATE_50
- ULTIMATE_100
=> Added ultimate sub plans.

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
JIRA - https://xero.atlassian.net/browse/PETOSS-478
=> Fix 478 | Model Syntax issue | PHP

xero-payroll-nz.yaml
NZP-4038 - NZ Payroll Working Pattern changes
NZP-4038 - NZ Payroll Working Pattern changes
EPIC [NZP-3350](https://xero.atlassian.net/browse/NZP-3350)
We will enable partners to manage employee working patterns for NZ Payroll
[NZP-3350]: https://xero.atlassian.net/browse/NZP-3350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NZP-4038 - NZ Payroll Working Pattern changes

xero-payroll-nz.yaml
- Add new fields for [NZ Payroll Holidays Act Update](https://developer.xero.com/documentation/api/changelog/payrollnz-holiday-act)
- 
Do not merge until 5 August when the features go live
=> NZP-3111 Add new fields for NZ Payroll Holidays Act Update

xero-payroll-nz.yaml
Working pattern changes was missing problem in one of the schemas
It is related to the NZ Payroll Working pattern changes
https://xero.atlassian.net/browse/NZP-4038
=> NZP-4038 - Missing problem in schema

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> OAS version update to 6.1.1

xero_accounting.yaml
Update documentation to reflect the fact that `SentToContact` is now writeable. Due for release Monday 26th August
This is related to [this work](https://xero.atlassian.net/browse/INVINP-1344) for modernized credit notes
=> INVINP-13442 | Credit notes now have SentToContact as writeable

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> OAS version update | 6.2.0

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Version update changes for OAS 6.3.0

xero-app-store.yaml, xero-finance.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml
=> PRISM Server Setup Changes

xero-app-store.yaml, xero-finance.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml
This reverts commit 4f14ed7deaf245fffc9e8ef5ba2a89eee9aa612c, reversing changes made to 7b219fef5016578a22e1dda04259e3fcc99a83ff.
=> Revert "Merge pull request #628 from XeroAPI/consume-prism-server"

.github/workflows/OAS-release.yml
=> PETOSS-588 | Added OAS release placeholder file

.github/semantic-release/package.json, .github/semantic-release/release.config.js, .github/workflows/OAS-release.yml, .gitignore
=> PETOSS 588 | Semantic Release Setup

.github/workflows/OAS-release.yml
=> 588 | Semantic release step fix

.github/semantic-release/release.config.js, .github/workflows/OAS-release.yml
=> PETOSS 588 | Semantic release config updates

.github/octokit/index.js, .github/octokit/package.json, .github/workflows/update-OAS-version.yml
=> PETOSS 588 | Pipeline | OAS version update for all spec yaml files

.github/workflows/pr-health-check.yml, README.md, commitlint.config.js, package-lock.json, package.json
=> PETOSS-588  | commit lint step added in pipeline

.github/workflows/pr-health-check.yml
=> 588 | updated PR health check trigger condition

README.md
=> ci: typo fix read me

xero_accounting.yaml
=> Fix | Prism | Request format changed from byte to binary for application/octet-stream

.github/workflows/pr-health-check.yml
=> feat: trigger commitlint check only on pr

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> OAS version update to 7.1.0

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
##CAB - 
https://xero.atlassian.net/browse/CAB-3961
=> OAS spec version update - 8.0.0

xero_accounting.yaml
=> [APIB-6718] Add SIMPLE org plan

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Updated OAS spec verison to - 8.1.0

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> Updated OAS spec version to 8.2.0

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> OAS version update - 8.3.0

xero_accounting.yaml
=> fixes response schema for getManualJournalAttachmentById

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
=> OAS spec update - 9.0.0

xero_accounting.yaml
Reverts XeroAPI/Xero-OpenAPI#737
=> Revert "[XBAP-22591] - Updated Date field decsription for Payment and Batchpayment endpoint"

xero-app-store.yaml, xero-finance.yaml, xero-identity.yaml, xero-payroll-au.yaml, xero-payroll-nz.yaml, xero-payroll-uk.yaml, xero-projects.yaml, xero_accounting.yaml, xero_assets.yaml, xero_bankfeeds.yaml, xero_files.yaml
Bumps OAS release number to 9.1.0
=> chore: bumps release number to 9.1.0
